.PHONY: clean All

All:
	@echo "----------Building project:[ PP12a - Debug ]----------"
	@cd "PP12a" && "$(MAKE)" -f  "PP12a.mk"
clean:
	@echo "----------Cleaning project:[ PP12a - Debug ]----------"
	@cd "PP12a" && "$(MAKE)" -f  "PP12a.mk" clean
