.PHONY: clean All

All:
	@echo "----------Building project:[ PP8a - Debug ]----------"
	@cd "C:\Users\User\Desktop\C1020\Workspaces\PP8a\PP8a" && "$(MAKE)" -f  "PP8a.mk"
clean:
	@echo "----------Cleaning project:[ PP8a - Debug ]----------"
	@cd "C:\Users\User\Desktop\C1020\Workspaces\PP8a\PP8a" && "$(MAKE)" -f  "PP8a.mk" clean
