.PHONY: clean All

All:
	@echo "----------Building project:[ C1020a12Lab4 - Debug ]----------"
	@cd "C1020a12Lab4" && "$(MAKE)" -f  "C1020a12Lab4.mk"
clean:
	@echo "----------Cleaning project:[ C1020a12Lab4 - Debug ]----------"
	@cd "C1020a12Lab4" && "$(MAKE)" -f  "C1020a12Lab4.mk" clean
