.PHONY: clean All

All:
	@echo "----------Building project:[ PP9b - Debug ]----------"
	@cd "PP9b" && "$(MAKE)" -f  "PP9b.mk"
clean:
	@echo "----------Cleaning project:[ PP9b - Debug ]----------"
	@cd "PP9b" && "$(MAKE)" -f  "PP9b.mk" clean
