.PHONY: clean All

All:
	@echo "----------Building project:[ C1020a12ExtraCredit - Debug ]----------"
	@cd "C1020a12ExtraCredit" && "$(MAKE)" -f  "C1020a12ExtraCredit.mk"
clean:
	@echo "----------Cleaning project:[ C1020a12ExtraCredit - Debug ]----------"
	@cd "C1020a12ExtraCredit" && "$(MAKE)" -f  "C1020a12ExtraCredit.mk" clean
