.PHONY: clean All

All:
	@echo "----------Building project:[ PP10-11 - Debug ]----------"
	@cd "PP10-11" && "$(MAKE)" -f  "PP10-11.mk"
clean:
	@echo "----------Cleaning project:[ PP10-11 - Debug ]----------"
	@cd "PP10-11" && "$(MAKE)" -f  "PP10-11.mk" clean
